### ISSUE TITLE
Shapes Dataset Release

### ISSUE THREAD

**Issue by bkpcoding** [locuslab/diffusion-model-hallucination#1]
Hello, thank you releasing the code. I was wondering, when do you plan to release the reproduction code for Shapes Dataset, I was conducting some experiments and wanted to check my hypothesis on that dataset.

**Comment by snehalstomar** [comment]
The dataset release would be very helpful.

**Comment by bkpcoding** [comment]
Actually, it is pretty simple to create one, I made an attempt, although I do not claim it to be the exact but it is close to what has been mentioned in the paper. Here:  https://github.com/bkpcoding/shapes_dataset

**Comment by sumukhaithal6** [comment]
Hello,
I have pushed the code for creating the shapes dataset in the shapes folder. Apologies for the delay.
